plugins { id 'com.android.application' }

dependencies { implementation 'androidx.core:core:1.13.1' }

android {
    namespace 'com.ofcos.productioncalculator'
    compileSdk 35
    defaultConfig {
        applicationId 'com.ofcos.productioncalculator.beginner'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

